//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototypeForAnkiEsque.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrototypeForAnkiEsque.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Flashcards.
        /// </summary>
        internal static string BttnAllFlashcards {
            get {
                return ResourceManager.GetString("BttnAllFlashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BttnBack {
            get {
                return ResourceManager.GetString("BttnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BttnDelete {
            get {
                return ResourceManager.GetString("BttnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Deck.
        /// </summary>
        internal static string BttnDeleteDeck {
            get {
                return ResourceManager.GetString("BttnDeleteDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string BttnEaseEasy {
            get {
                return ResourceManager.GetString("BttnEaseEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string BttnEaseGood {
            get {
                return ResourceManager.GetString("BttnEaseGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string BttnEaseHard {
            get {
                return ResourceManager.GetString("BttnEaseHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BttnEdit {
            get {
                return ResourceManager.GetString("BttnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Deck.
        /// </summary>
        internal static string BttnEditDeck {
            get {
                return ResourceManager.GetString("BttnEditDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Decks.
        /// </summary>
        internal static string BttnExportDeck {
            get {
                return ResourceManager.GetString("BttnExportDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Flashcards.
        /// </summary>
        internal static string BttnExportFlashcards {
            get {
                return ResourceManager.GetString("BttnExportFlashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip card.
        /// </summary>
        internal static string BttnFlip {
            get {
                return ResourceManager.GetString("BttnFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Decks.
        /// </summary>
        internal static string BttnImportDeck {
            get {
                return ResourceManager.GetString("BttnImportDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Flaschards.
        /// </summary>
        internal static string BttnImportFlashcards {
            get {
                return ResourceManager.GetString("BttnImportFlashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string BttnMainMenu {
            get {
                return ResourceManager.GetString("BttnMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new deck.
        /// </summary>
        internal static string BttnNewDeck {
            get {
                return ResourceManager.GetString("BttnNewDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Flashcard.
        /// </summary>
        internal static string BttnNewFlashcard {
            get {
                return ResourceManager.GetString("BttnNewFlashcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string BttnNext {
            get {
                return ResourceManager.GetString("BttnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        internal static string BttnNextPage {
            get {
                return ResourceManager.GetString("BttnNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        internal static string BttnPreviousPage {
            get {
                return ResourceManager.GetString("BttnPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Deck.
        /// </summary>
        internal static string BttnReview {
            get {
                return ResourceManager.GetString("BttnReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string BttnSave {
            get {
                return ResourceManager.GetString("BttnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Deck.
        /// </summary>
        internal static string BttnSelectDeck {
            get {
                return ResourceManager.GetString("BttnSelectDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string GrdHdrBack {
            get {
                return ResourceManager.GetString("GrdHdrBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck name.
        /// </summary>
        internal static string GrdHdrDeckName {
            get {
                return ResourceManager.GetString("GrdHdrDeckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease rating.
        /// </summary>
        internal static string GrdHdrEase {
            get {
                return ResourceManager.GetString("GrdHdrEase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        internal static string GrdHdrFront {
            get {
                return ResourceManager.GetString("GrdHdrFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string GrdHdrProgress {
            get {
                return ResourceManager.GetString("GrdHdrProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string GrdHdrSelection {
            get {
                return ResourceManager.GetString("GrdHdrSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this flashcard?.
        /// </summary>
        internal static string MsgDeleteFlashcard {
            get {
                return ResourceManager.GetString("MsgDeleteFlashcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete flashcard.
        /// </summary>
        internal static string MsgDeleteFlashcardConfirmation {
            get {
                return ResourceManager.GetString("MsgDeleteFlashcardConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting flashcard!.
        /// </summary>
        internal static string MsgDeleteFlashcardError {
            get {
                return ResourceManager.GetString("MsgDeleteFlashcardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this deck?.
        /// </summary>
        internal static string MssgDeckDeletionConfirmation {
            get {
                return ResourceManager.GetString("MssgDeckDeletionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading decks!.
        /// </summary>
        internal static string MssgDeckLoadError {
            get {
                return ResourceManager.GetString("MssgDeckLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! You&apos;re mastering this card..
        /// </summary>
        internal static string MssgEaseButtonEasy {
            get {
                return ResourceManager.GetString("MssgEaseButtonEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good! You&apos;re doing well..
        /// </summary>
        internal static string MssgEaseButtonGood {
            get {
                return ResourceManager.GetString("MssgEaseButtonGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep going! You&apos;ll get it soon..
        /// </summary>
        internal static string MssgEaseButtonHard {
            get {
                return ResourceManager.GetString("MssgEaseButtonHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flashcard cannot have blank sides!.
        /// </summary>
        internal static string MssgFlashcardBlankError {
            get {
                return ResourceManager.GetString("MssgFlashcardBlankError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This flashcard already exists!.
        /// </summary>
        internal static string MssgFlashcardDuplicateError {
            get {
                return ResourceManager.GetString("MssgFlashcardDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Flashcard to save!.
        /// </summary>
        internal static string MssgFlashcardMissingError {
            get {
                return ResourceManager.GetString("MssgFlashcardMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcard saved successfully!.
        /// </summary>
        internal static string MssgFlashcardSaveSuccess {
            get {
                return ResourceManager.GetString("MssgFlashcardSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done - you finished the deck!.
        /// </summary>
        internal static string MssgMotivationalMessage {
            get {
                return ResourceManager.GetString("MssgMotivationalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving flashcard!.
        /// </summary>
        internal static string MssgSaveFlashcardError {
            get {
                return ResourceManager.GetString("MssgSaveFlashcardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error!.
        /// </summary>
        internal static string MssgValidationError {
            get {
                return ResourceManager.GetString("MssgValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter back:.
        /// </summary>
        internal static string TxtBlkEnterBack {
            get {
                return ResourceManager.GetString("TxtBlkEnterBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter front:.
        /// </summary>
        internal static string TxtBlkEnterFront {
            get {
                return ResourceManager.GetString("TxtBlkEnterFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string TxtBlkSearch {
            get {
                return ResourceManager.GetString("TxtBlkSearch", resourceCulture);
            }
        }
    }
}
